baseURL = "https://danielwiese.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Daniel Wiese"
theme = "hermit"
pygmentsCodefences  = true
pygmentsUseClasses  = true

[author]
  name = "Daniel Wiese"

[taxonomies]
  tag = "tags"

[params]
  description = "My writings and resources on engineering, technology, programming, aviation and more."
  images = ["img/og-image.jpeg"]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  themeColor = "#494f5c"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  customCSS = ["css/code.css", "css/style.css"]

  # Social Icons
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/dpwiese/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/danielpwiese"

  [[params.social]]
    name = "github"
    url = "https://github.com/dpwiese"

[menu]

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Resources"
    url = "resources/"
    weight = 20

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20

[markup]

  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true # otherwise copying code blocks copies the numbers

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
