baseURL = "https://danielwiese.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Daniel P. Wiese"
theme = "hermit"

[author]
  name = "Daniel P. Wiese"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  themeColor = "#494f5c"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Social Icons
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/dpwiese/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/danielpwiese"

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/dpwiese"

  [[params.social]]
    name = "github"
    url = "https://github.com/dpwiese"
